### ISSUE TITLE
Example not working and iOS support

### ISSUE THREAD

**Issue by eug48** [jacksonjude/cloudkit_flutter#1]
Thanks for an interesting project!

Firstly, I noticed the example doesn't work with `flutter build` - presumably some files like `pubspec.yaml` are missing?

Secondly, the README states that the usefulness on iOS is limited - I'd be interested to learn more about this and whether you think it's tractable to improve iOS support via this approach?

**Comment by jacksonjude** [comment]
Thanks for noticing the problems with the example code, I've pushed a new update here and to pub.dev which has a full project with building capabilities within the example/ directory.

Onto your other question: The short answer is simply that native CloudKit support is better on iOS, especially because the user is likely already signed into their iCloud account via the device itself, meaning the web api method I've employed here would be quite redundant. In addition, other iOS-specific methods exist to take the CloudKit support further, such as the official [CoreData + CloudKit syncronization engine via NSPersistentCloudKitContainer](https://developer.apple.com/documentation/coredata/mirroring_a_core_data_store_with_cloudkit/setting_up_core_data_with_cloudkit), or third-party packages like [CloudCore](https://github.com/deeje/CloudCore).

So, although the package does *technically* work on iOS, the developer ease-of-use & user experience are inferior to iOS-specific alternatives.
